from django.urls import path
from . import views
	
urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('about/', views.about, name='about'),
    path('about/team', views.about_team, name='about_team'),
    path('about/technology', views.about_technology, name='about_technology'),
    path('products/', views.products_index, name='products_index'),
    path('products/<str:tcin>', views.products_detail, name='products_detail'),
    path('products/<str:tcin>/items/new', views.items_new, name='items_new'),
    path('products/<str:tcin>/items/create', views.items_create, name='items_create'),
    path('items/<int:id>/payment', views.items_payment, name='items_payment'),
    path('items/<int:id>/buy', views.items_buy, name='items_buy'),
    path('items/<int:id>/received', views.items_received, name='items_received'),
    path('items/<int:id>/edit', views.items_edit, name='items_edit'),
    path('items/<int:id>/update', views.items_update, name='items_update'),
    path('items/<int:pk>/delete', views.ItemDelete.as_view(), name='items_delete'),
    path('items/<int:id>/review/new', views.reviews_new, name='reviews_new'),
    path('items/<int:id>/review/create', views.reviews_create, name='reviews_create'),
    path('items/<int:id>/confirm', views.items_create_confirm, name='items_create_confirm'),
    path('items/<int:id>/bought', views.items_bought_confirm, name='items_bought_confirm'),
    path('items/<int:item_id>/reviews/<int:review_id>/edit', views.reviews_edit, name='reviews_edit'),
    path('items/<int:item_id>/reviews/<int:review_id>/update', views.reviews_update, name='reviews_update'),
    path('items/<int:item_id>/reviews/<int:review_id>/delete', views.reviews_delete, name='reviews_delete'),
    path('accounts/buying/pending', views.buying_pending, name='buying_pending'),
    path('accounts/buying/history', views.buying_history, name='buying_history'),
    path('accounts/buying/reviews', views.buying_reviews, name='buying_reviews'),
    path('accounts/selling/listing', views.selling_listing, name='selling_listing'),
    path('accounts/selling/pending', views.selling_pending, name='selling_pending'),
    path('accounts/selling/history', views.selling_history, name='selling_history'),
    path('accounts/selling/reviews', views.selling_reviews, name='selling_reviews'),
    path('seller/<int:id>/reviews', views.seller_reviews, name='seller_reviews'),
    path('seller/<int:id>/listing', views.seller_listing, name='seller_listing'),
]